### ISSUE TITLE
Why each dataset is paired with only one inference engine?

### ISSUE THREAD

**Issue by ziadloo** [teacherpeterpan/Logic-LLM#3]
Perhaps, the answer to my question is very obvious but at least not to me. Why each dataset is paired with only one inference engine? For example, why are you using Pyke to solve ProntoQA questions and not all the IEs you've got?

Granted, if you decide to use different IEs for the same dataset, per each IE you have to use the LLM to generate the proper syntax for it and that will add to the cost. But still, I believe it would be much more valuable if each dataset is solved using all the IEs.

**Comment by teacherpeterpan** [comment]
Thanks for asking. Different symbolic solvers are made to solve different types of problems. For example, Pyke supports forward-/backward-chain reasoning, that's why we use it for ProntoQA. However, Pyke does not support first-order logic reasoning, which is why we cannot use it to solve problems in FOLIO. There is no symbolic solver that can solve any type of logical reasoning problem. That's why we integrate multiple solvers to tailor for different types of problems. Hope this helps to answer your question.
